# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: none
PRINT_ALPACA: false

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# See https://megalinter.io/8.8.0/flavors/java/ for possible linters
#ENABLE_LINTERS:
#  - ACTION_ACTIONLINT
#  - JAVA_CHECKSTYLE
#  - MARKDOWN_MARKDOWN_LINK_CHECK
#  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
#  - MARKDOWN_MARKDOWNLINT
#  - REPOSITORY_CHECKOV
#  - REPOSITORY_GIT_DIFF
#  - REPOSITORY_GITLEAKS
#  - REPOSITORY_SECRETLINT
#  - REPOSITORY_SYFT
#  - REPOSITORY_TRIVY
#  - REPOSITORY_TRIVY_SBOM
#  - REPOSITORY_TRUFFLEHOG
#  - YAML_V8R
#  - YAML_YAMLLINT
#  # - COPYPASTE_JSCPD
#  # - EDITORCONFIG_EDITORCONFIG_CHECKER
#  # - JAVA_PMD
#  # - JSON_V8R
#  # - JSON_JSONLINT
#  # - JSON_PRETTIER
#  # - XML_XMLLINT
#  # - YAML_PRETTIER

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - JAVA_PMD
  - JSON_V8R
  - JSON_JSONLINT
  - JSON_PRETTIER
  - XML_XMLLINT
  - YAML_PRETTIER

YAML_FILTER_REGEX_INCLUDE: '(\.github/.*|[^/]+\.yml)'

# https://megalinter.io/8.8.0/descriptors/java_checkstyle/
JAVA_CHECKSTYLE_CONFIG_FILE: '.checkstyle.xml'
JAVA_CHECKSTYLE_FILTER_REGEX_INCLUDE: 'src/main'


# MegaLinter should detect errors but not block CI to pass
DISABLE_ERRORS: true
