sudo: false

language: java
jdk: oraclejdk8

script: mvn clean verify jacoco:report coveralls:report -B -U

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/952357dbd9d3cea70fd5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
