# Builds the project with Java 8.

name: Java 8 build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B --file pom.xml package jacoco:report

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        if: github.event_name != 'pull_request'
        with:
          base-path: src/main/java
          # The file is optional, but the documentation says it's better to specify it.
          file: target/site/jacoco/jacoco.xml

