# Builds the project with Java 8.

name: Java 8 build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B --file pom.xml package jacoco:report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
