# Builds the project with Java 8.

name: Java 8 build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      coveralls_repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B --file pom.xml package jacoco:report

      # Set environment variables for Coveralls. Copied from https://github.com/trautonen/coveralls-maven-plugin/issues/136
      - name: "Report: Coverage via coveralls.io"
        # GITHUB_HEAD_REF is only available during PRs; disable this step as Coveralls doesn't work with PRs
        # https://docs.github.com/en/actions/learn-github-actions/environment-variables
        if: 'GITHUB_HEAD_REF == null'
        run: |
          export CI_BRANCH=${BRANCH_NAME_OR_REF#refs/heads/}
          export CI_PULL_REQUEST=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          mvn coveralls:report -e --no-transfer-progress -DrepoToken=${{ secrets.COVERALLS_TOKEN }}
        env:
          CI_NAME: github
          BRANCH_NAME_OR_REF: ${{ github.head_ref || github.ref }}
          CI_BUILD_NUMBER: ${{ github.run_id }}
          CI_BUILD_URL: https://github.com/${{ github.repository }}/commit/${{ github.event.after }}/checks
          COVERALLS_SECRET: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
